/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/axios-client'
import type {
  CreateArticleArticlesPostMutationRequest,
  CreateArticleArticlesPostMutationResponse,
  CreateArticleArticlesPost422,
} from '../types/CreateArticleArticlesPost.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/axios-client'

function getCreateArticleArticlesPostUrl() {
  const res = { method: 'POST', url: `/articles` as const }
  return res
}

/**
 * @summary Create Article
 * {@link /articles}
 */
export async function createArticleArticlesPost(
  data: CreateArticleArticlesPostMutationRequest,
  config: Partial<RequestConfig<CreateArticleArticlesPostMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data
  const res = await request<
    CreateArticleArticlesPostMutationResponse,
    ResponseErrorConfig<CreateArticleArticlesPost422>,
    CreateArticleArticlesPostMutationRequest
  >({ method: 'POST', url: getCreateArticleArticlesPostUrl().url.toString(), data: requestData, ...requestConfig })
  return res.data
}