/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/axios-client'
import type { ListArticlesArticlesGetQueryResponse } from '../types/ListArticlesArticlesGet.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/axios-client'

function getListArticlesArticlesGetUrl() {
  const res = { method: 'GET', url: `/articles` as const }
  return res
}

/**
 * @summary List Articles
 * {@link /articles}
 */
export async function listArticlesArticlesGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<ListArticlesArticlesGetQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: getListArticlesArticlesGetUrl().url.toString(),
    ...requestConfig,
  })
  return res.data
}