/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/axios-client'
import type { LoginLoginPostMutationRequest, LoginLoginPostMutationResponse, LoginLoginPost422 } from '../types/LoginLoginPost.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/axios-client'

function getLoginLoginPostUrl() {
  const res = { method: 'POST', url: `/login` as const }
  return res
}

/**
 * @summary Login
 * {@link /login}
 */
export async function loginLoginPost(
  data: LoginLoginPostMutationRequest,
  config: Partial<RequestConfig<LoginLoginPostMutationRequest>> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data
  const res = await request<LoginLoginPostMutationResponse, ResponseErrorConfig<LoginLoginPost422>, LoginLoginPostMutationRequest>({
    method: 'POST',
    url: getLoginLoginPostUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  })
  return res.data
}