/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const operations = {
  login_login_post: {
    path: '/login',
    method: 'post',
  },
  list_articles_articles_get: {
    path: '/articles',
    method: 'get',
  },
  create_article_articles_post: {
    path: '/articles',
    method: 'post',
  },
} as const