/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Article = {
  /**
   * @type integer
   */
  id: number
  /**
   * @type string
   */
  title: string
  /**
   * @type string
   */
  body: string
}