/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ArticleCreateDto = {
  /**
   * @type string
   */
  title: string
  /**
   * @type string
   */
  body: string
}