/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ArticleCreateDto } from './ArticleCreateDto.ts'
import type { HTTPValidationError } from './HTTPValidationError.ts'

/**
 * @description Successful Response
 */
export type CreateArticleArticlesPost200 = any

/**
 * @description Validation Error
 */
export type CreateArticleArticlesPost422 = HTTPValidationError

export type CreateArticleArticlesPostMutationRequest = ArticleCreateDto

export type CreateArticleArticlesPostMutationResponse = CreateArticleArticlesPost200

export type CreateArticleArticlesPostMutation = {
  Response: CreateArticleArticlesPost200
  Request: CreateArticleArticlesPostMutationRequest
  Errors: CreateArticleArticlesPost422
}