/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ValidationError } from './ValidationError.ts'

export type HTTPValidationError = {
  /**
   * @type array | undefined
   */
  detail?: ValidationError[]
}