/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Article } from './Article.ts'

/**
 * @description Successful Response
 */
export type ListArticlesArticlesGet200 = Article[]

export type ListArticlesArticlesGetQueryResponse = ListArticlesArticlesGet200

export type ListArticlesArticlesGetQuery = {
  Response: ListArticlesArticlesGet200
  Errors: any
}