/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from './HTTPValidationError.ts'
import type { LoginDto } from './LoginDto.ts'

/**
 * @description Successful Response
 */
export type LoginLoginPost200 = any

/**
 * @description Validation Error
 */
export type LoginLoginPost422 = HTTPValidationError

export type LoginLoginPostMutationRequest = LoginDto

export type LoginLoginPostMutationResponse = LoginLoginPost200

export type LoginLoginPostMutation = {
  Response: LoginLoginPost200
  Request: LoginLoginPostMutationRequest
  Errors: LoginLoginPost422
}