/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type LoginDto = {
  /**
   * @type string
   */
  username: string
  /**
   * @type string
   */
  password: string
}