/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ValidationError = {
  /**
   * @type array
   */
  loc: (string | number)[]
  /**
   * @type string
   */
  msg: string
  /**
   * @type string
   */
  type: string
}